mod 'registry',
:git => 'https://github.com/puppetlabs/puppetlabs-registry'

mod 'powershell',
:git => 'https://github.com/puppetlabs/puppetlabs-powershell'

mod 'stdlib',
:git => 'https://github.com/puppetlabs/puppetlabs-stdlib'

mod 'chocolatey',
:git => 'https://github.com/chocolatey/puppet-chocolatey'

mod 'download_file',
:git => 'https://github.com/puppet-community/puppet-download_file'

mod 'inifile',
:git => 'https://github.com/puppetlabs/puppetlabs-inifile'

mod 'windows',
:git => 'https://github.com/counsyl/puppet-windows'

mod 'windows_base',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_base'

mod 'windows_role_base',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_role_base'

mod 'windows_oradb',
:git => 'https://github.com/naturalis/puppet-windows_oradb'

mod 'windows_role_oradb',
:git => 'https://github.com/naturalis/puppet-windows_role_oradb'

#mod 'topdesk',
#:git => 'https://github.com/rudibroekhuizen/puppet-topdesk'

#mod 'role_topdesk',
#:git => 'https://github.com/rudibroekhuizen/puppet-role_topdesk'

mod 'windows_logstash',
:git    => 'https://github.com/rudibroekhuizen/puppet-windows_logstash'
#:branch => "develop"

mod 'windows_role_logstash',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_role_logstash'

mod 'windows_burp',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_burp'

mod 'filebeat',
:git => 'https://github.com/pcfens/puppet-filebeat'

# Used by filebeat module:
mod 'remote_file',
:git => 'https://github.com/lwf/puppet-remote_file'
