# Installs from the puppet forge
#mod "chocolatey/chocolatey"
#mod "badgerious/windows_env"
#mod "opentable/download_file"
#mod "counsyl/windows"
#mod "puppetlabs/stdlib"
#mod "puppetlabs/powershell"
#mod "puppetlabs/registry"

# Installs from git
mod 'registry',
:git => 'https://github.com/puppetlabs/puppetlabs-registry'

mod 'powershell',
:git => 'https://github.com/puppetlabs/puppetlabs-powershell'

mod 'stdlib',
:git => 'https://github.com/puppetlabs/puppetlabs-stdlib'

mod 'chocolatey',
:git => 'https://github.com/chocolatey/puppet-chocolatey'

mod 'download_file',
:git => 'https://github.com/puppet-community/puppet-download_file'

mod 'windows',
:git => 'https://github.com/counsyl/puppet-windows'

mod 'windows_base',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_base'

mod 'windows_role_base',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_role_base'

mod 'windows_oradb',
:git => 'https://github.com/naturalis/puppet-windows_oradb'

mod 'windows_role_oradb',
:git => 'https://github.com/naturalis/puppet-windows_role_oradb'

#mod 'topdesk',
#:git => 'https://github.com/rudibroekhuizen/puppet-topdesk'

#mod 'role_topdesk',
#:git => 'https://github.com/rudibroekhuizen/puppet-role_topdesk'

mod 'windows_logstash',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_logstash'
:ref => "develop"

mod 'windows_role_logstash',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_role_logstash'

mod 'windows_burp',
:git => 'https://github.com/rudibroekhuizen/puppet-windows_burp'
